version: 2.1

jobs:
  build:
    working_directory: ~/nology-project
    docker:
      - image: "circleci/python:3.10 .7"
    steps:
      - checkout
      - run: npm run start
  test:
    working_directory: ~/nology-project
    docker:
      - image: "circleci/python:3.10.7"
    steps:
      - checkout
      - run: npm run start

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build